### ISSUE TITLE
Got multiple errors when trying to compile chapter 1 project

### ISSUE THREAD

**Issue by tuhdo** [GameHackingBook/GameHackingExamples#1]
Hi,

I am trying to compile chapter 1 project, but it seems to be missing something (I already installed Allegro though  NuGet)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		identifier "BYTE" is undefined	Chapter1_BasicMemory	c:\Users\Tu Do\visual studio 2015\Projects\GameHackingExamples\Chapter1_BasicMemory\game-BasicMem.cpp	15	
Error (active)		identifier "ZeroMemory" is undefined	Chapter1_BasicMemory	c:\Users\Tu Do\visual studio 2015\Projects\GameHackingExamples\Chapter1_BasicMemory\game-BasicMem.cpp	103	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	15	
Error	C2146	syntax error: missing ';' before identifier 'map'	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	15	
Error	C2065	'map': undeclared identifier	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	21	
Error	C2065	'map': undeclared identifier	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	28	
Error	C2065	'map': undeclared identifier	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	30	
Error	C2065	'map': undeclared identifier	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	32	
Error	C2065	'map': undeclared identifier	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	34	
Error	C2065	'map': undeclared identifier	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	86	
Error	C3861	'ZeroMemory': identifier not found	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	103	
Error	C2065	'map': undeclared identifier	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	113	
Warning	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	Chapter1_BasicMemory	c:\users\tu do\visual studio 2015\projects\gamehackingexamples\chapter1_basicmemory\game-basicmem.cpp	105	
```

I have been working on Linux, so I'm really not familiar with Windows toolchain, like VS. I hope you could help me on this. Thanks.

**Comment by tuhdo** [comment]
@nickcano Ok I found out how to compile it with the latest Allegro 5.2 installed from NuGet with this guide: https://wiki.allegro.cc/index.php?title=Windows,_Visual_Studio_2015_and_Nuget_Allegro_5. I was going to recompile Allegro and manually link it myself, which would waste tons of time. Thanks to the guide for an easier way.

Even I installed the VC++ 2010 redistributable package but it still shows me the error like "failed to initialize map!" or "failed to initialize font!". Fortunately, it only happens with binaries from Chapter 1 to 3.

**Comment by nickcano** [comment]
@tuhdo For the map and font errors, just move the game.map and arial.tff into the same folder as the executable.

I'll work on hammering out the build errors. I think I'll just either add the allegro libraries in a dependencies folder beside the project, or add the allegro source to be compiled with the rest of the project. Thanks for the feedback!

**Comment by tuhdo** [comment]
@nickcano I already built chapter 1 to 3 with the latest 5.2 Allegro from NuGet (using the guide above) and it worked correctly (and I also completed chapter 1 exercises). 

Building manually myself is fine. I should be clearer that the error "failed to initialize map!" or "failed to initialize font!" happens only when using pre-built binaries, not the ones I built myself. Indeed, copying the `game` and `arial.tff` fixed the problem. You should include those in the `bin` directory instead putting it outside.

**Comment by a-harper** [comment]
Sorry to open this one up again - I've tried going through the guide linked, and added Fonts and Memory to the Allegro addons but I'm still getting the big error list posted in the OP. Any ideas?

**Comment by nickcano** [comment]
@a-harper Is there some reason you want to compile the labs binaries other than for doing the labs? There are binaries included inside of the repository that you can use for the labs. Compiling them yourself is nice but there's no actual need to compile them.

The code starting at Chapter 4 should compile without a hitch, everything before that is technically a lab and will rely on the correct version of allegro to properly compile.

**Comment by a-harper** [comment]
@nickcano Curiosity mostly! The binary does work after copying the map & font files in though, yeah. We had an awful time converting from VS2010 to 2015 at work so suspect it's something about that process causing the problem here too.

Thanks for the response!

**Comment by JulianDavis** [comment]
@nickcano This issue still exist on your github

As @tuhdo mentioned:

>  I should be clearer that the error "failed to initialize map!" or "failed to initialize font!" happens only when using pre-built binaries, not the ones I built myself. Indeed, copying the game and arial.tff fixed the problem. You should include those in the bin directory instead putting it outside.

Copying the `arial.tff` and `game.map` files into the bin allowed me to run the pre-compiled `Chapter1_BasicMemory` but without copying those files over I was getting the error "failed to initialize map"

It's fixed now thanks to this post, but it is confusing for the first chapter to be broken and this seems the be the only Google result on the subject.
