### ISSUE TITLE
Freezing pointers crashes Chapter1_MemoryPointers.exe

### ISSUE THREAD

**Issue by ghost** [GameHackingBook/GameHackingExamples#9]
Hi, hoping there's some support for this book as I recently purchased from No Starch Press. I believe I found the correct pointers for this exercise because I can close and restart Chapter1_MemoryPointers.exe and the pointers still affect the ball's X and Y values. 

However, when I freeze the pointer values in Cheat Engine 6.7 and run the test (to win 50 times) the exe crashes. What am I doing wrong? 

Let me know if you need any additional info.

**Comment by sriese** [comment]
I was having the same issue, this article helped: https://guidedhacking.com/threads/game-hacking-code-book-help.9291 

Essentially what's not clear is the initial pointer we are using was not the correct one. It appears that the statement in the book _"If you have a handful of seemingly usable chains, grab the one with the fewest offsets"_ is not correct as the working pointer had one of the longer offset chains.

I still haven't found a concrete way to clearly identify the right pointer on the first try.

**Comment by GH-Rake** [comment]
After filtering your pointer list several times you should choose the one with the least number of offsets, if it stops working, use the next one.  This is the correct method.

**Comment by Cheaterz** [comment]
Hi everyone, GuidedHacking is now paid, does anybody have the solution posted there? Thanks.
